// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMvc.Models;

namespace ProjectMvc.Migrations.SubCategory
{
    [DbContext(typeof(SubCategoryContext))]
    partial class SubCategoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectMvc.Models.SubCategory", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Briefdetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GST")
                        .HasColumnType("real");

                    b.Property<int>("Sub_id")
                        .HasColumnType("int");

                    b.Property<string>("Sub_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cid");

                    b.ToTable("SubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
